#!/bin/sh
# This script was created by make-mzscheme-launcher

# {{{ bindir
bindir="/usr/bin"
# }}} bindir

exec "${bindir}/racket" -N "$0" '-t' '/home/marwin/projects/todo/todo.rkt' '-U' '--'  ${1+"$@"}
