((3) 1 ((#"/home/marwin/projects/todo/entity.rkt" . deserialize-info:Todo-entry-v0)) 0 () () (0 1 "lol todo"))
((3) 1 ((#"/home/marwin/projects/todo/entity.rkt" . deserialize-info:Todo-entry-v0)) 0 () () (0 3 "lol todo asdf "))
((3) 1 ((#"/home/marwin/projects/todo/entity.rkt" . deserialize-info:Todo-entry-v0)) 0 () () (0 4 "loooool"))
((3) 1 ((#"/home/marwin/projects/todo/entity.rkt" . deserialize-info:Todo-entry-v0)) 0 () () (0 5 "adf"))
